config/routes.rb
Rails.application.routes.draw do

  get 'orders/:id/braintree/new' => 'braintree#new', as: :braintree_new
  post 'orders/:id/braintree/checkout' => 'braintree#checkout', as: :braintree_checkout

  get 'orders/edit'

  get 'orders/update'

  get 'orders/destroy'

  get 'foods/new'

  get 'foods/create'

  get 'foods/show'

  get 'foods/destroy'

  # get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users do
    # collection do
    #   get 'checkname'
    # end
  end
	
  resources :foods, controller: "foods" do 
    resources :orders, only: [:create, :new]
	end 

  resources :orders
	resource :logins, only: [:create, :destroy]

	root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
	belongs_to :user
	has_many :orders, dependent: :destroy

	scope :search_bar, -> (search_bar) { where("name ILIKE ?", "%#{search_bar}%")}
	scope :search, -> (name) { where name: name}
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :food

	enum payment: [ false, true ]

	def pay
	 	self.update(payment: 1)
	end

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :email, presence: true
	validates :email, uniqueness: true

	enum role: [ :customer, :vendor ] 

	has_one :food, dependent: :destroy
	has_many :orders, dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?, :vendor_food, :customer_order
  private
  
  def current_user
    @current_user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def vendor_food
  	Food.where(user_id: current_user.id)
  end

  def customer_order
    x = []
    @order = Order.where(user_id: current_user.id)

  	@order.each do |o|
      x << Food.find(o.food_id)
    end

    x
  end

  def current_order
    x = Order.where(:user_id => :current_user_id, :listing => ["active", "deleted"])
  end

end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
	  @order = Order.find(params[:id])
		@client_token = Braintree::ClientToken.generate
  end

  def checkout
    @order = Order.find(params[:id])
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    result = Braintree::Transaction.sale(
     :amount => Food.find(@order.food_id).price, #this is currently hardcoded
     :payment_method_nonce => nonce_from_the_client,
     :options => {
        :submit_for_settlement => true
      }
     )

    if result.success?
      @order.pay
      redirect_to :root, :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
	
	def index
    x = params[:search_bar]
    if x 
      @food = Food.search_bar(x)
    else

  		@food = Food.all

      filtering_params(params).each do |key, value|
        @food = @food.public_send(key, value) if value.present?
      end
      
    end 
	end

  def new
  	@food = Food.new
  end

  def create
  	@food = current_user.build_food(food_params)

  	if @food.save
  		redirect_to foods_path, :flash => { :success => "Successfully created food listing!" }
  	else
  		redirect_to new_food_path, :notice => "Failed to create food listing"
  	end
  end

  def show
    @food = Food.find(params[:id])
    @order = Order.new
  end

  def destroy
  end

  private

  def food_params
  	params.require(:food).permit(:name, :cuisine, :price, :location)
  end

  def filtering_params(params)
      params.slice(:search)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if logged_in?
  		redirect_to users_path
  	end
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

	def create
		@user = User.find_by(email:params[:logins][:email])
		if @user
		  if @user.authenticate(params[:logins][:password])
		    session[:current_user_id] = @user.id
		    redirect_to users_path, :notice => "Logged in!"
		  else
		  	redirect_to root_path, :notice => "Invalid email or password!"
		  end
		else 
			redirect_to root_path, :notice => "No such account exist!"
		end
	end

	def destroy
	  # Remove the user id from the session
	  @_current_user = session[:current_user_id] = nil
	  redirect_to root_path, :notice => "Logged out!"
	  reset_session
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
  end

  def create
    # @food = Food.find(params[:food_id])
    @order = current_user.orders.new(order_params)
    @order.food_id = params[:food_id]
    # byebug
    if @order.save
      redirect_to users_path, :notice => "Order success"
    else
      redirect_to users_path, :notice => "Failed"
    end

  end

  def edit
  end

  def update
  end

  def destroy
    # byebug
    @order = Order.find(params[:id])
    @order.destroy.to_json
    # redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:delivery_time)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	# def checkname
 #    if User.where('name = ?', params[:name]).count == 0
 #      render :nothing => true, :status => 200
 #    else
 #      render :nothing => true, :status => 409
 #    end
 #    return
 #  end


	def index
		if current_user.vendor?
			@food = vendor_food
		else
			@food = customer_order
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:current_user_id] = @user.id
			redirect_to root_path, :flash => { :success => "Successful!" }
		else
			redirect_to new_user_path
		end

	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/braintree/new.html.erb
<div class="demo-frame">

  <%= form_for :checkout_form, url: braintree_checkout_path(@order.id), html: { id: "cardForm"} do |form| %>

  <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
  <div id="card-number" class="hosted-field"></div>

  <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
  <div id="expiration-date" class="hosted-field"></div>

  <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
  <div id="cvv" class="hosted-field"></div>

  <%= form.hidden_field "payment_method_nonce" %>

  <div class="button-container">
    <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
  </div>
<% end %>
</div>


<script>
      var form = document.querySelector('#cardForm');
      var submit = document.querySelector("#submit-payment-btn");

      braintree.client.create({
        authorization: "<%= @client_token %>"
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          console.error(clientErr);
          return;
        }

        // This example shows Hosted Fields, but you can also use this
        // client instance to create additional components here, such as
        // PayPal or Data Collector.

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '14px'
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }
          },
          fields: {
            number: {
              selector: '#card-number',
              placeholder: '4111 1111 1111 1111'
            },
            cvv: {
              selector: '#cvv',
              placeholder: '123'
            },
            expirationDate: {
              selector: '#expiration-date',
              placeholder: '10/2019'
            }
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            console.error(hostedFieldsErr);
            return;
          }

          submit.removeAttribute('disabled');

          form.addEventListener('submit', function (event) {
            event.preventDefault();

            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
              }

              // If this was a real integration, this is where you would
              // send the nonce to your server.
              document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
                      form.submit();
            });
          }, false);
        });
      });
    </script>

app/views/foods/_form.html.erb
<div>
	<%= form_for @food do |f| %>
		<div>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div>
			<%= f.label :cuisine %>
			<%= f.text_field :cuisine %>
		</div>
		<div>
			<%= f.label :price %>
			<%= f.number_field :price %>
		</div>
		<div>
			<%= f.label :location %>
			<%= f.text_field :location %>
		</div>
		<div class="submit-field">
			<%= f.submit %>
		</div>
		<% end %>	
</div>

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/index.html.erb
<h1>Food Index</h1>

<table>
	<tr>
		<th>No.</th>
		<th>Name</th>
		<th>Type</th>
		<th>Price</th>
		<th>Location</th>
	</tr>
<% @food.each do |x| %>
	<tr>
		<td> <%= x.id=%> </td>
		<td> <%= link_to x.name, food_path(x.id) %> </td>
		<td> <%= x.cuisine %> </td>
		<td> RM <%= x.price %> </td>
		<td> <%= x.location %> </td>
	</tr>
<% end %>

</table>

app/views/foods/new.html.erb
<h1>Create food listing</h1>

<%= render partial: '/foods/form' %> 

app/views/foods/show.html.erb
<h1><%= @food.name %> Page</h1>

<p> <%= @food.id=%> </p>
<p> <%= @food.cuisine %> </p>
<p> RM <%= @food.price %> </p>
<p> <%= @food.location %> </p>

<div>
	<h2> <b>Book Now!</b></h2>
	<%= form_for [@food, @order] do |form| %>

	 <%= form.text_field :delivery_time, id: "datetimepicker" %>
	   <div class="submit-field">
	     <%= form.submit "Order Now!" , :class => 'calendar-submit', :style =>" margin-bottom: 10px; margin-left: 40px; width: 120px; height: 40px; border: 2px solid orange; background-color: white; color: orange; border-radius: 5px;"%>
	   </div>
	<% end %>

	 <script type="text/javascript">
	   $(document).ready(function(){
	     jQuery('#datetimepicker').datetimepicker({
	       inline: true
	     });
	   });
	 </script>

</div>

app/views/home/index.html.erb
<h1>Home</h1>

<div>
	<%= form_for :logins, url: logins_path, method: :create do |f| %>
		<div>
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>
		<div>
			<%= f.label :password %>
			<%= f.text_field :password %>
		</div>
		<div class="submit-field">
			<%= f.submit "Log in"%>
		</div>
	<% end %>	
</div>

<p><%= link_to "Sign Up", new_user_path %></p>
<% if logged_in? %>
<p><%= link_to "Log Out", logins_path, method: :delete %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodpanda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!--     <link rel="stylesheet" type="text/css" href="/jquery.datetimepicker.css"/ >
    <script src="/jquery.js"></script>
    <script src="/build/jquery.datetimepicker.full.min.js"></script> -->



    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.14/jquery.datetimepicker.css">

    <!-- Load the Client component. -->
    <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

    <!-- Load the Hosted Fields component. -->
    <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.14/jquery.datetimepicker.full.js"></script>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload" %>


  </head>
  <% flash.each do |key, msg| %>
      <%= content_tag :div, msg, id: key %>
  <% end %>
  <body>
    <%= yield %>
    <%= link_to "Home", root_path %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/users/_form.html.erb
<div>
	<%= form_for @user do |f| %>
		<div id="name">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div id="email">
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>
		<div id="pass">
			<%= f.label :password %>
			<%= f.text_field :password %>
		</div>
		<div class="submit-field">
			<%= f.submit "Sign Up"%>
		</div>
	<% end %>	
</div>

app/views/users/index.html.erb
<h1>Hi <%= current_user.role %> <%= current_user.name %></h1>

<div>
	<%= form_tag foods_path, :method => 'get' do %>
	   <!-- <p>   -->
	        <%= label_tag :search_name %>
	        <%= text_field_tag :search_bar, params[:search_bar] %>
	    <!-- </p> -->
	   <%= submit_tag "Search" %>
	<% end %>

	<%= form_tag(foods_path, method: :get) do %>
	  <%= select_tag :search, options_from_collection_for_select(Food.select(:name).distinct.order(:name),"name","name")%>
	  <%= submit_tag 'Search'%>
	<%end%>
</div>

<% if logged_in? %>
<p><%= link_to "Log Out", logins_path, method: :delete %></p>
<% end %>

<% if current_user.customer? %>
	<p><%= link_to "Check out foods to order", foods_path %></p>
<% else %>
	<% if current_user.food == false %>
		<p><%= link_to "Create new food listing", new_food_path %></p>
	<% end %>
<% end %>

<div>
	<table id="table">
		<tr>
			<th>No.</th>
			<th>Name</th>
			<th>Type</th>
			<th>Price</th>
			<th>Location</th>
			<th>Payment</th>
			<th> </th>
		</tr>
	<% @food.each do |x| %>
		<tr id="<%= Order.find_by_user_id_and_food_id(current_user.id, x.id).id %>">
			<td> <%= x.id=%> </td>
			<td> <%= link_to x.name, food_path(x.id) %> </td>
			<td> <%= x.cuisine %> </td>
			<td> RM <%= x.price %> </td>
			<td> <%= x.location %> </td>
			<td>
				<% unless Order.find_by_user_id_and_food_id(current_user.id, x.id).payment? %>
					<%= link_to "Make Payment", braintree_new_path(Order.find_by_user_id_and_food_id(current_user.id, x.id).id) %>
				<% else %>	
					Paid!
				<% end %>
			</td>
			<!-- <td> <%#= button_to "Delete", order_path(Order.find_by_user_id_and_food_id(current_user.id, x.id).id), method: :delete %> </td> -->
			<td class="destroy"> Delete </td>
		</tr>
	<% end %>

	</table>
</div>

app/views/users/new.html.erb
<h1>Sign up/in</h1> 

<%= render partial: '/users/form' %> 